sudo: false

language: python
python: 3.5

cache:
  pip: true

# command to install dependencies
install: "pip install -U tox"

# # command to run tests
env:
  # coveralls is not listed in tox's envlist, but should run in travis
  #- TOXENV=coveralls
  # note: please use "tox --listenvs" to populate the build matrix below
  #- TOXENV=linting
  #- TOXENV=py26
  #- TOXENV=py27
  #- TOXENV=py33
  #- TOXENV=py34
  #- TOXENV=py35
  #- TOXENV=pypy
  #- TOXENV=py27-pexpect
  #- TOXENV=py27-xdist
  #- TOXENV=py27-trial
  #- TOXENV=py35-pexpect
  #- TOXENV=py35-xdist
  #- TOXENV=py35-trial
  #- TOXENV=py27-nobyte
  #- TOXENV=doctesting
  #- TOXENV=py27-cxfreeze
  - TOXENV=py27-cython

script: tox -e $TOXENV

#notifications:
#  irc:
#    channels:
#      - "chat.freenode.net#pytest"
#    on_success: change
#    on_failure: change
#    skip_join: true
#  email:
#    - pytest-commit@python.org
